spring.application.name=UniTrade Backend
# Server
server.port=8080

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/unitrade_db
spring.datasource.username=root
spring.datasource.password=Harsh@70

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

file.upload.dir=D:/UniTradeProject/unitrade/unitrade-backend/uploads

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

twilio.account.sid=ACbadcc67e38fe99c595fa5108b79e2cd9
twilio.auth.token=c8e271d5d1f88c63dde622864d3788d6
twilio.whatsapp.from=whatsapp:+14155238886
